services:

  tests:
    build:
      context: ..
      dockerfile: Monero.Test/Dockerfile
    depends_on:
      - xmr_wallet

  monerod:
    image: btcpayserver/monero:0.18.4.1
    container_name: monerod
    command: monerod --fixed-difficulty 1 --log-level=2 --rpc-bind-ip=0.0.0.0 --confirm-external-bind --rpc-bind-port=18081 --rpc-access-control-origins=* --block-notify="/bin/sh ./scripts/notifier.sh -k -X GET https://host.docker.internal:14142/monerolikedaemoncallback/block?cryptoCode=xmr&hash=%s" --regtest --no-igd --hide-my-port --offline --non-interactive
    volumes:
      - xmr_data:/data
    ports:
      - "18081:18081"

  xmr_wallet:
    image: btcpayserver/monero:0.18.4.1
    container_name: xmr_wallet
    command: monero-wallet-rpc --log-level 2 --allow-mismatched-daemon-version --rpc-bind-ip=0.0.0.0 --disable-rpc-login --confirm-external-bind --rpc-bind-port=28082 --non-interactive --trusted-daemon --daemon-address=monerod:18081 --wallet-dir=/wallet --rpc-access-control-origins=* --tx-notify="/bin/sh ./scripts/notifier.sh -k -X GET https://host.docker.internal:14142/monerolikedaemoncallback/tx?cryptoCode=xmr&hash=%s"
    ports:
      - "18082:18082"
    volumes:
      - xmr_wallet:/wallet
    depends_on:
      - monerod

volumes:
  xmr_data:
  xmr_wallet:
    