name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Initialize
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Clean project
        run: dotnet clean

      - name: Build
        run: dotnet build --no-restore

      - name: Run integration tests
        run: docker compose -f Monero.Test/docker-compose.yml run tests
    
      - name: Cleanup Docker containers
        if: always()
        run: docker compose -f Monero.Test/docker-compose.yml down -v
