name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Initialize
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Clean project
        run: dotnet clean

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Run unit tests
        run: |
          dotnet tool install --global JetBrains.dotCover.CommandLineTools --version 2025.1.6
          dotCover cover-dotnet --TargetArguments="test Monero.UnitTests/Monero.UnitTests.csproj -c Release --no-build" --output=coverage/dotCover.UnitTests.output.dcvr

      - name: Run integration tests
        run: docker compose -f Monero.IntegrationTests/docker-compose.yml run tests
    
      - name: Cleanup Docker containers
        if: always()
        run: docker compose -f Monero.IntegrationTests/docker-compose.yml down -v

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/dotcover.xml
